version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/reporting/Dockerfile
    container_name: guardian-reporting
    env_file:
      - ./app/.env
      - ./app/.env.db
      - ./app/.env.redis
    environment:
      POSTGRES_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
      LOG_FILE: /app/logs/guardian-reporting.log
      DATA_DIRECTORY: /var/lib/guardian/data
    tty: true
    volumes:
      - reporting_log:/app/logs,tmpfs,uid=1001,gid=1001
      - reporting_data:/var/lib/guardian/data

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: guardian-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis-dev.conf"]

volumes:
    reporting_data:
    reporting_log:
