# In addition to a local log file we also also write log data to stdout.
# Using stdout for logging makes onboarding to Atlas/Goat log broker system from OpenShift very easy.

version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    filename: guardian-reporting.log
    formatter: standard

  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: standard

loggers:
  reporting:
    handlers: [file, console]
    level: INFO
    propagate: no
#  reporting.error:
#    handlers: [file, console]
#    level: ERROR
#    propagate: no

root:
  handlers: [console, file]
  level: INFO
